Repository Kehindecodes/simply-appointments-backend, pull requests merged in 2024-07, with the labels that each got.

#3 Developfixed
  compose.yaml
  src/.gitIgnore
  src/entity/Service.ts
  src/entity/User.ts
  src/enum/Currency.ts
  src/routes/user.route.ts
Labels: good first issue

#8 implement login with OTP notification
  package-lock.json
  package.json
  src/entity/OTP.ts
  src/entity/Role.ts
  src/entity/User.ts
  src/enum/UserTypes.ts
  src/enum/userTypes.enum.ts
  src/index.ts
  src/middlewares/authorizeUser.ts
  src/middlewares/jwtAuthentication.ts
  src/migration/data-source.ts
  src/routes/Role/role.route.ts
  src/routes/User/user.controller.ts
  src/routes/User/user.route.ts
  src/services/nodemailer-config.ts
  src/services/passport-config.ts
  src/tests/user.controller.spec.ts
  src/utils/otp.utils.ts
Labels: enhancement

#5 added files
  src/entity/Address.ts
  src/entity/Appointment.ts
  src/entity/Profile.ts
  src/entity/Review.ts
  src/entity/Service.ts
  src/enum/Category.ts
  src/enum/Status.ts
  src/enum/currency.enum.ts
  src/httpResponse-handler/errorHandler.ts
  src/httpResponse-handler/successHandler.ts
  src/index.ts
  src/middlewares/checkAppointment.ts
  src/middlewares/checkService.ts
  src/migration/data-source.ts
  src/model/response-status.ts
  src/routes/Apppointment/appointment.controller.ts
  src/routes/Apppointment/appointment.route.ts
  src/routes/Service/service.controller.ts
  src/routes/Service/service.route.ts
  src/routes/User/user.route.ts
  src/tests/service.controller.spec.ts
  src/types/custom-express.d.ts
Labels: documentation
